name: epitopepredict
version: '0.5.0'
summary: python package for MHC binding prediction
description: |
 epitopepredict is a python package and command line interface that provides a standardized
 programmatic interface for executing several MHC binding prediction methods. The results from
 each method can then be processed and visualized in a consistent manner.

base: core18
grade: stable
confinement: strict
icon: snap/gui/icon.png

apps:
  epitopepredict:
    command: bin/epitopepredict
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - network-control
      - mount-observe
      - removable-media
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/ncbi-blast+
parts:
  epitopepredict:
    plugin: python
    source: .
    python-packages:
      - bokeh
      - panel
      #- mhcflurry
    stage-packages:
      - gawk
      - ncbi-blast+
      - tcsh
